

chill_person_view:
    pattern: /view/{id}
    defaults: { _controller: ChillPersonBundle:Person:view }
    options:
        menu: person
        order: 50
        label: menu.person.general_view
        
chill_person_general_edit:
    pattern: /view/{id}/edit
    defaults: {_controller: ChillPersonBundle:Person:edit }
    
chill_person_general_update:
    pattern: /view/{id}/update
    defaults: {_controller: ChillPersonBundle:Person:update }
    
chill_person_new:
    pattern: /new
    defaults: {_controller: ChillPersonBundle:Person:new }
    
chill_person_review:
    pattern: /review
    defaults: {_controller: ChillPersonBundle:Person:review }
    
chill_person_create:
    pattern: /create
    defaults: {_controller: ChillPersonBundle:Person:create }
    
    
chill_person_search:
    pattern: /search
    defaults: { _controller: ChillPersonBundle:Person:search }      
        
chill_person_history_list:
    pattern: /{id}/history
    defaults: { _controller: ChillPersonBundle:History:list }
    options:
        menu: person
        order: 100
        label: menu.person.history
        
chill_person_history_create:
    pattern: /{personId}/history/create
    defaults: { _controller: ChillPersonBundle:History:create }
    

chill_person_history_update:
    pattern: /{id}/history/{historyId}/update
    defaults: { _controller: ChillPersonBundle:History:update }   
    
chill_person_history_close:
    pattern: /{id}/history/close
    defaults: { _controller: ChillPersonBundle:History:close }
    
chill_person_history_open:
    pattern: /{id}/history/open
    defaults: { _controller: ChillPersonBundle:History:open }
    
chill_person_admin:
    pattern: /admin
    defaults: { _controller: ChillPersonBundle:Admin:index }
    options:
        menu: admin
        order: 100
        label: menu.person.admin.index
        helper: menu.person.admin.helper

#sample admin_person menu:
chill_person_admin_test_one:
    pattern: /admin/test_one
    defaults: { _controller: ChillPersonBundle:Admin:test }
    options:
        menu: admin_person
        order: 100
        label: menu.person.admin.test_one
        helper: menu.person.admin.helper_one
        
#sample
chill_appointment_list:
    pattern: /view/{id}/appointment/list
    defaults: {_controller: ChillPersonBundle:Person:view}
    options:
        menu: person
        order: 200
        label: "Rendez-vous"
        
chill_prof_status_view:
    pattern: /view/{id}/prof/list
    defaults: {_controller: ChillPersonBundle:Person:view}
    options:
        menu: person
        order: 300
        label: "Statut Professionnel"
        
chill_admin_view:
    pattern: /view/{id}/administrative
    defaults: {_controller: ChillPersonBundle:Person:view}
    options:
        menu: person
        order: 400
        label: "Statut administratif"
        
chill_language:
    pattern: /view/{id}/language/list
    defaults: {_controller: ChillPersonBundle:Person:view}
    options:
        menu: person
        order: 500
        label: "Langues"    
        
chill_studies:
    pattern: /view/{id}/studies
    defaults: {_controller: ChillPersonBundle:Person:view}
    options:
        menu: person
        order: 600
        label: "Études"
        
chill_notes:
    pattern: /view/{id}/notes
    defaults: {_controller: ChillPersonBundle:Person:view}
    options:
        menu: person
        order: 700
        label: "Informations"
        
chill_docs:
    pattern: /view/{id}/docs
    defaults: {_controller: ChillPersonBundle:Person:view}
    options:
        menu: person
        order: 800
        label: "Documents"
